import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { 
  FileStack,
  Plus,
  Copy,
  Trash2,
  Edit,
  CheckCircle,
  XCircle,
  AlertTriangle,
  ChevronRight,
  Briefcase
} from "lucide-react";
import { toast } from "sonner";

export default function Templates() {
  const [selectedTemplate, setSelectedTemplate] = useState<number | null>(null);
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isAddItemDialogOpen, setIsAddItemDialogOpen] = useState(false);
  const [newTemplate, setNewTemplate] = useState({
    name: "",
    description: "",
    position: "",
    isBase: false,
  });
  const [newItem, setNewItem] = useState({
    documentTypeId: "",
    isRequired: true,
    hasExpiration: false,
    expirationDays: "",
    alertDaysBefore: "30",
    requiresSignature: false,
    isAutoGenerated: false,
  });

  const { data: templates, isLoading, refetch } = trpc.templates.list.useQuery();
  const { data: templateDetail } = trpc.templates.get.useQuery(
    { id: selectedTemplate! },
    { enabled: !!selectedTemplate }
  );
  const { data: documentTypes } = trpc.documentTypes.list.useQuery();
  const { data: departments } = trpc.departments.list.useQuery();

  const createTemplate = trpc.templates.create.useMutation({
    onSuccess: () => {
      toast.success("Template criado com sucesso!");
      setIsCreateDialogOpen(false);
      setNewTemplate({ name: "", description: "", position: "", isBase: false });
      refetch();
    },
    onError: (error) => toast.error(`Erro: ${error.message}`),
  });

  const addItem = trpc.templates.addItem.useMutation({
    onSuccess: () => {
      toast.success("Item adicionado!");
      setIsAddItemDialogOpen(false);
      setNewItem({
        documentTypeId: "",
        isRequired: true,
        hasExpiration: false,
        expirationDays: "",
        alertDaysBefore: "30",
        requiresSignature: false,
        isAutoGenerated: false,
      });
      refetch();
    },
    onError: (error) => toast.error(`Erro: ${error.message}`),
  });

  const removeItem = trpc.templates.removeItem.useMutation({
    onSuccess: () => {
      toast.success("Item removido!");
      refetch();
    },
  });

  const duplicateTemplate = trpc.templates.duplicate.useMutation({
    onSuccess: () => {
      toast.success("Template duplicado!");
      refetch();
    },
  });

  const initDefaults = trpc.templates.initDefaults.useMutation({
    onSuccess: () => {
      toast.success("Templates padrão criados!");
      refetch();
    },
  });

  const handleCreateTemplate = () => {
    if (!newTemplate.name) {
      toast.error("Nome é obrigatório");
      return;
    }
    createTemplate.mutate({
      name: newTemplate.name,
      description: newTemplate.description || undefined,
      position: newTemplate.position || undefined,
      isBase: newTemplate.isBase,
    });
  };

  const handleAddItem = () => {
    if (!newItem.documentTypeId || !selectedTemplate) {
      toast.error("Selecione um tipo de documento");
      return;
    }
    addItem.mutate({
      templateId: selectedTemplate,
      documentTypeId: parseInt(newItem.documentTypeId),
      isRequired: newItem.isRequired,
      hasExpiration: newItem.hasExpiration,
      expirationDays: newItem.expirationDays ? parseInt(newItem.expirationDays) : undefined,
      alertDaysBefore: parseInt(newItem.alertDaysBefore),
      requiresSignature: newItem.requiresSignature,
      isAutoGenerated: newItem.isAutoGenerated,
    });
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-64" />
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[1, 2, 3].map((i) => (
            <Skeleton key={i} className="h-40" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Templates de Documentos</h1>
          <p className="text-slate-500 mt-1">Defina pacotes de documentos por cargo ou função</p>
        </div>
        <div className="flex gap-2">
          {(!templates || templates.length === 0) && (
            <Button 
              variant="outline" 
              onClick={() => initDefaults.mutate()}
              disabled={initDefaults.isPending}
            >
              Criar Templates Padrão
            </Button>
          )}
          <Button onClick={() => setIsCreateDialogOpen(true)} className="bg-blue-600 hover:bg-blue-700">
            <Plus className="h-4 w-4 mr-2" />
            Novo Template
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Lista de Templates */}
        <div className="lg:col-span-1 space-y-4">
          <h2 className="font-semibold text-slate-700">Templates Disponíveis</h2>
          {templates?.map((template) => (
            <Card 
              key={template.id}
              className={`cursor-pointer transition-all hover:shadow-md ${
                selectedTemplate === template.id ? 'ring-2 ring-blue-500' : ''
              }`}
              onClick={() => setSelectedTemplate(template.id)}
            >
              <CardContent className="p-4">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-blue-50 rounded-lg">
                      <FileStack className="h-5 w-5 text-blue-600" />
                    </div>
                    <div>
                      <h3 className="font-medium text-slate-900">{template.name}</h3>
                      {template.position && (
                        <div className="flex items-center gap-1 text-sm text-slate-500">
                          <Briefcase className="h-3 w-3" />
                          {template.position}
                        </div>
                      )}
                    </div>
                  </div>
                  <div className="flex gap-1">
                    {template.isBase && (
                      <Badge variant="secondary" className="text-xs">Base</Badge>
                    )}
                    {template.isActive ? (
                      <Badge className="bg-emerald-100 text-emerald-700 text-xs">Ativo</Badge>
                    ) : (
                      <Badge variant="outline" className="text-xs">Inativo</Badge>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
          
          {(!templates || templates.length === 0) && (
            <Card className="border-dashed">
              <CardContent className="py-8 text-center">
                <FileStack className="h-10 w-10 mx-auto text-slate-300 mb-3" />
                <p className="text-slate-500">Nenhum template criado</p>
                <p className="text-sm text-slate-400 mt-1">
                  Clique em "Criar Templates Padrão" para começar
                </p>
              </CardContent>
            </Card>
          )}
        </div>

        {/* Detalhes do Template */}
        <div className="lg:col-span-2">
          {selectedTemplate && templateDetail ? (
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>{templateDetail.template.name}</CardTitle>
                    <CardDescription>
                      {templateDetail.template.description || "Sem descrição"}
                    </CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        const newName = prompt("Nome do novo template:", `${templateDetail.template.name} (Cópia)`);
                        if (newName) {
                          duplicateTemplate.mutate({
                            templateId: selectedTemplate,
                            newName,
                          });
                        }
                      }}
                    >
                      <Copy className="h-4 w-4 mr-1" />
                      Duplicar
                    </Button>
                    <Button
                      size="sm"
                      onClick={() => setIsAddItemDialogOpen(true)}
                    >
                      <Plus className="h-4 w-4 mr-1" />
                      Adicionar Documento
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center justify-between text-sm text-slate-500 border-b pb-2">
                    <span>Documentos do Template ({templateDetail.items.length})</span>
                    {templateDetail.template.parentTemplateId && (
                      <span className="text-blue-600">Herda do template base</span>
                    )}
                  </div>
                  
                  {templateDetail.items.map((item, index) => (
                    <div 
                      key={item.id}
                      className="flex items-center justify-between p-3 bg-slate-50 rounded-lg"
                    >
                      <div className="flex items-center gap-3">
                        <span className="text-sm font-medium text-slate-400 w-6">
                          {index + 1}.
                        </span>
                        <div>
                          <p className="font-medium text-slate-900">
                            {item.documentType?.name || `Tipo #${item.documentTypeId}`}
                          </p>
                          <div className="flex gap-2 mt-1">
                            {item.isRequired && (
                              <Badge variant="outline" className="text-xs">Obrigatório</Badge>
                            )}
                            {item.hasExpiration && (
                              <Badge variant="outline" className="text-xs text-amber-600 border-amber-200">
                                Validade: {item.expirationDays} dias
                              </Badge>
                            )}
                            {item.requiresSignature && (
                              <Badge variant="outline" className="text-xs text-blue-600 border-blue-200">
                                Assinatura
                              </Badge>
                            )}
                            {item.isAutoGenerated && (
                              <Badge variant="outline" className="text-xs text-emerald-600 border-emerald-200">
                                Auto-gerado
                              </Badge>
                            )}
                          </div>
                        </div>
                      </div>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="text-red-500 hover:text-red-700 hover:bg-red-50"
                        onClick={() => removeItem.mutate({ id: item.id })}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  ))}
                  
                  {templateDetail.items.length === 0 && (
                    <div className="text-center py-8 text-slate-500">
                      <AlertTriangle className="h-8 w-8 mx-auto text-amber-400 mb-2" />
                      <p>Nenhum documento no template</p>
                      <p className="text-sm">Adicione documentos para definir o pacote</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          ) : (
            <Card className="h-full flex items-center justify-center">
              <CardContent className="text-center py-12">
                <ChevronRight className="h-12 w-12 mx-auto text-slate-300 mb-4" />
                <h3 className="text-lg font-medium text-slate-600">Selecione um template</h3>
                <p className="text-slate-400 mt-1">
                  Clique em um template à esquerda para ver os detalhes
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>

      {/* Dialog: Criar Template */}
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Novo Template de Documentos</DialogTitle>
            <DialogDescription>
              Crie um pacote de documentos para um cargo ou função específica
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>Nome do Template *</Label>
              <Input
                value={newTemplate.name}
                onChange={(e) => setNewTemplate({ ...newTemplate, name: e.target.value })}
                placeholder="Ex: Template Motorista"
              />
            </div>
            <div>
              <Label>Descrição</Label>
              <Input
                value={newTemplate.description}
                onChange={(e) => setNewTemplate({ ...newTemplate, description: e.target.value })}
                placeholder="Descrição do template"
              />
            </div>
            <div>
              <Label>Cargo/Posição</Label>
              <Input
                value={newTemplate.position}
                onChange={(e) => setNewTemplate({ ...newTemplate, position: e.target.value })}
                placeholder="Ex: Motorista, Vendedor, Produção"
              />
            </div>
            <div className="flex items-center gap-2">
              <Checkbox
                id="isBase"
                checked={newTemplate.isBase}
                onCheckedChange={(checked) => setNewTemplate({ ...newTemplate, isBase: !!checked })}
              />
              <Label htmlFor="isBase" className="font-normal">
                Template base (aplicável a todos os funcionários)
              </Label>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsCreateDialogOpen(false)}>
              Cancelar
            </Button>
            <Button onClick={handleCreateTemplate} disabled={createTemplate.isPending}>
              Criar Template
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Dialog: Adicionar Item */}
      <Dialog open={isAddItemDialogOpen} onOpenChange={setIsAddItemDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Adicionar Documento ao Template</DialogTitle>
            <DialogDescription>
              Defina um tipo de documento e suas configurações
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>Tipo de Documento *</Label>
              <Select
                value={newItem.documentTypeId}
                onValueChange={(v) => setNewItem({ ...newItem, documentTypeId: v })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Selecione o tipo" />
                </SelectTrigger>
                <SelectContent>
                  {documentTypes?.map((dt) => (
                    <SelectItem key={dt.id} value={dt.id.toString()}>
                      {dt.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="flex items-center gap-2">
                <Checkbox
                  id="isRequired"
                  checked={newItem.isRequired}
                  onCheckedChange={(checked) => setNewItem({ ...newItem, isRequired: !!checked })}
                />
                <Label htmlFor="isRequired" className="font-normal">Obrigatório</Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  id="requiresSignature"
                  checked={newItem.requiresSignature}
                  onCheckedChange={(checked) => setNewItem({ ...newItem, requiresSignature: !!checked })}
                />
                <Label htmlFor="requiresSignature" className="font-normal">Requer Assinatura</Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  id="hasExpiration"
                  checked={newItem.hasExpiration}
                  onCheckedChange={(checked) => setNewItem({ ...newItem, hasExpiration: !!checked })}
                />
                <Label htmlFor="hasExpiration" className="font-normal">Tem Validade</Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  id="isAutoGenerated"
                  checked={newItem.isAutoGenerated}
                  onCheckedChange={(checked) => setNewItem({ ...newItem, isAutoGenerated: !!checked })}
                />
                <Label htmlFor="isAutoGenerated" className="font-normal">Auto-gerado</Label>
              </div>
            </div>
            
            {newItem.hasExpiration && (
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label>Validade (dias)</Label>
                  <Input
                    type="number"
                    value={newItem.expirationDays}
                    onChange={(e) => setNewItem({ ...newItem, expirationDays: e.target.value })}
                    placeholder="365"
                  />
                </div>
                <div>
                  <Label>Alertar antes (dias)</Label>
                  <Input
                    type="number"
                    value={newItem.alertDaysBefore}
                    onChange={(e) => setNewItem({ ...newItem, alertDaysBefore: e.target.value })}
                    placeholder="30"
                  />
                </div>
              </div>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsAddItemDialogOpen(false)}>
              Cancelar
            </Button>
            <Button onClick={handleAddItem} disabled={addItem.isPending}>
              Adicionar
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
